---
- name: "Analyse {{filename}}"
  shell: "chdir=~/anayser python -m bin.main run ~/reports/ycsb/ ~/reports/analyser//{{ansible_date_time.epoch}}_analysis.csv"
  register: out

- debug: msg="{{ out.stdout }}"

