---
- hosts: local
  connection: local
  tasks:
  - name: Use role in loop
    include_role:
      name: run_benchmark
    vars:
      - description: "{{ item.description }}"
      - db: "{{ item.db }}"
      - write_consistency: "{{ item.write_consistency }}"
      - read_consistency: "{{ item.read_consistency }}"
      - threads: "{{ item.threads }}"
      - objects_num: "{{ item.objects_num }}"
      - version_num: "{{ item.version_num }}"
      - with_network_faults: "{{ item.with_network_faults }}"
      - fault_duration: "{{ item.fault_duration }}"
      - fault_interval: "{{ item.fault_interval }}"
    with_items:
        - { description: cassandra, db: cassandra-cql, write_consistency: ALL, read_consistency: ALL, threads: 2, objects_num: 1000, version_num: 2, with_network_faults: true, fault_duration: 2, fault_interval: 40 }
        # - { description: cassandra, db: cassandra-cql, write_consistency: ALL, read_consistency: ALL, threads: 2, objects_num: 10, version_num: 1 }
        #- { description: cassandra, db: cassandra-cql, write_consistency: QUORUM, read_consistency: ONE, threads: 4, objects_num: 100, version_num: 3 }
        #- { description: cassandra, db: cassandra-cql, write_consistency: ONE, read_consistency: QUORUM, threads: 4, objects_num: 100, version_num: 3 }
        #- { description: cassandra, db: cassandra-cql, write_consistency: QUORUM, read_consistency: QUORUM, threads: 4, objects_num: 100, version_num: 3 }
        #- { description: riak, db: riak, write_consistency: ONE, read_consistency: ONE, threads: 4, objects_num: 100, version_num: 3 }
        #- { description: riak, db: riak, write_consistency: ALL, read_consistency: ALL, threads: 4, objects_num: 100, version_num: 3 }
        #- { description: riak, db: riak, write_consistency: QUORUM, read_consistency: ONE, threads: 4, objects_num: 100, version_num: 3 }
        #- { description: riak, db: riak, write_consistency: ONE, read_consistency: QUORUM, threads: 4, objects_num: 100, version_num: 3 }
        #- { description: riak, db: riak, write_consistency: QUORUM, read_consistency: QUORUM, threads: 4, objects_num: 100, version_num: 3 }
