 ---
- hosts: cassandra_cluster
  gather_facts: yes
  remote_user: ubuntu
  become: yes
  roles:
    - setup_cassandra
- hosts: cassandra_cluster
  gather_facts: yes
  remote_user: ubuntu
  become: yes
  roles:
    - setup_riak
- hosts: couchdb_cluster
  gather_facts: yes
  remote_user: ubuntu
  become: yes
  roles:
    - setup_couchdb
    
