---
- hosts: all
  remote_user: ubuntu
  gather_facts: yes
  become: yes
  roles:
    - setup_cassandra
    
- hosts: all
  remote_user: ubuntu
  gather_facts: yes
  become: yes
  roles:
    - setup_riak
    
