---
- name: With AWS instances started
  local_action:
    module: ec2
    aws_access_key: "{{aws_access_key}}"
    aws_secret_key: "{{aws_secret_key}}"
    region: eu-west-1
    wait: yes
    instance_tags:
        Name: node
    state: running

- name: "Load {{description}} write_consistency={{write_consistency}}, read_consistency={{read_consistency}}"
  shell: "chdir={{ycsb_home}} ./bin/ycsb load {{db}} -p hosts=\"{{load_balancer_ip_address}}\" -p threadcount={{threads}} -p objectversionlimit={{version_num}} -p numobjects={{objects_num}} -p cassandra.readconsistencylevel={{read_consistency}} -p cassandra.writeconsistencylevel={{write_consistency}} -P workloads/myworkload -s"
- name: "Run {{description}} write_consistency={{write_consistency}}, read_consistency={{read_consistency}}"
  shell: "chdir={{ycsb_home}} ./bin/ycsb run {{db}} -p hosts=\"{{load_balancer_ip_address}}\" -p threadcount={{threads}} -p objectversionlimit={{version_num}} -p numobjects={{objects_num}} -p cassandra.readconsistencylevel={{read_consistency}} -p cassandra.writeconsistencylevel={{write_consistency}} -P workloads/myworkload -s > {{results_home}}/{{ansible_date_time.epoch}}_{{description}}_w{{write_consistency}}_r{{read_consistency}}.dat"

- name: Reboot AWS instances
  local_action:
    module: ec2
    aws_access_key: "{{aws_access_key}}"
    aws_secret_key: "{{aws_secret_key}}"
    region: eu-west-1
    wait: yes
    instance_tags:
        Name: node
    state: restarted

