---
- name: Add local hostname to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    line: "127.0.0.1 {{ansible_hostname}}"
    state: present
  become: yes
- name: Update apt
  apt:
    update_cache: yes
    upgrade: yes
    allow-unauthenticated: yes
- name: install openjdk-8-jdk
  apt:
    name: openjdk-8-jre
- name: install maven
  apt:
    name: maven
- name: install python
  apt:
    name: python

