---
- name: Create Riak Keyspace
  shell: "cqlsh -e \"CREATE KEYSPACE IF NOT EXISTS ycsb WITH REPLICATION = { 'class' : 'SimpleStrategy', 'replication_factor' : 3 };\""
- name: Create Workload Table
  shell: "cqlsh -e \"USE ycsb; CREATE TABLE IF NOT EXISTS workload (y_id varchar primary key, version varchar);\""